### ISSUE TITLE
有关女装

### ISSUE THREAD

**Issue by ghost** [RimoChan/sese-engine#1]
> 要可爱的，最好是白发贫乳傲娇双马尾。

女装白发贫乳傲娇双马尾但可能没那么可爱的要嘛😃

（PS：试了几个关键词但迟迟不出结果，准备在本地部署再试一次。）

**Comment by RimoChan** [comment]
奇怪，服务应该没崩啊……然后本地部署的话你大概要先放1个月才能搜索……
女装，好！

**Comment by cyb233** [comment]
> 奇怪，服务应该没崩啊……然后本地部署的话你大概要先放1个月才能搜索…… 女装，好！

好耶，可以色色
xp重叠度：高😀
~~（什么时候也能成为一只大佬呢）~~

**Comment by ghost** [comment]
> > 奇怪，服务应该没崩啊……然后本地部署的话你大概要先放1个月才能搜索…… 女装，好！
> 
> 好耶，可以色色
> xp重叠度：高😀
> ~~（什么时候也能成为一只大佬呢）~~

我参考了一部分南大戏剧社翻译的《女装入门到精通》（原书名未知）。其他的女装技巧大概看看贴吧知乎的帖子就行了。重要的还是实践，嗯😜

~~感觉这个issue开始歪了（~~

**Comment by RimoChan** [comment]
好，那我们把这个issue改成有关女装吧！

**Comment by cyb233** [comment]
> 
> 我参考了一部分南大戏剧社翻译的《女装入门到精通》（原书名未知）。其他的女装技巧大概看看贴吧知乎的帖子就行了。重要的还是实践，嗯😜
> 
> ~感觉这个issue开始歪了（~

确实歪了（
~~我想说和 @RimoChan 的xp完全重合来着~~

**Comment by YUASDS** [comment]
> > 我参考了一部分南大戏剧社翻译的《女装入门到精通》（原书名未知）。其他的女装技巧大概看看贴吧知乎的帖子就行了。重要的还是实践，嗯😜
> > ~感觉这个issue开始歪了（~
> 
> 确实歪了（ ~我想说和 @RimoChan 的xp完全重合来着~

这个issue已经歪了
~但是没问题~

**Comment by Lumysia** [comment]
~~Mtf路过~~

**Comment by CofinCup** [comment]
（草 仓库主是不是在心惊报的频道活动过，怎么贴纸和风格都是熟悉的感觉）

**Comment by RimoChan** [comment]
> （草 仓库主是不是在心惊报的频道活动过，怎么贴纸和风格都是熟悉的感觉）

好，我的美名已经从爱尔兰到契丹无人不知无人不晓啦！
