### ISSUE TITLE
这个怎么好多都是中文的

### ISSUE THREAD

**Issue by wulintang** [RimoChan/sese-engine#12]
服务器无法配置，代码中有不能编码的文字，说明编译环境有点问题，这个本地是可以运行的，封装到容器后，字符解码不了，默认是英文语言状态，中文环境需要另外设置。

**Comment by RimoChan** [comment]
本地可以运行就说明环境应该是没问题的，对吧，然后docker我不熟，帮不了你啊……

**Comment by wulintang** [comment]
> 本地可以运行就说明环境应该是没问题的，对吧，然后docker我不熟，帮不了你啊……

部署到宝塔上吧，提示的全是没有“启动.sh”然后看来看去，就是py在服务器不支持中文，用docker的版本弄到宝塔里吧，没有任何数据。
