### ISSUE TITLE
[Feature Request] 支持将色色引擎添加到浏览器的搜索引擎列表

### ISSUE THREAD

**Issue by AtomAlpaca** [RimoChan/sese-engine#15]
如题，我希望将色色引擎的官方 Demo 站 [`sese.yyj.moe`](https://sese.yyj.moe) 添加到 `Firefox` 浏览器的搜索引擎列表，以便在地址栏通过该引擎进行搜索。
我参考了[这篇文章](https://support.mozilla.org/en-US/kb/add-or-remove-search-engine-firefox)，但是没有发现将该网站添加到搜索引擎列表的选项。请问色色引擎在将来是否会支持此功能？

我使用的浏览器是 `Firefox v100.0.2(64 bit)`

**Comment by RimoChan** [comment]
我觉得这个功能可以有，不过我没有很想要……我们来问问 @yunyoujun 吧！

(还有你多打了一个引擎)

**Comment by RimoChan** [comment]
不过这个issue是前端的issue，所以应该写到 YunYouJun/sese-engine-ui 这个仓库里，然后我没有前端仓库的写权限，所以没法用Transfer issue的功能转移过去……

**Comment by YunYouJun** [comment]
> 不过这个issue是前端的issue，所以应该写到 YunYouJun/sese-engine-ui 这个仓库里，然后我没有前端仓库的写权限，所以没法用Transfer issue的功能转移过去……

![image](https://user-images.githubusercontent.com/25154432/170071599-5e317e09-79e3-47d2-a37e-2377b72ba245.png)

我记得你是有的……

**Comment by YunYouJun** [comment]
我认为这是默认支持。

譬如：

<img width="683" alt="image" src="https://user-images.githubusercontent.com/25154432/170072278-39be4eac-2240-4e04-88b3-a26504b5966a.png">

<img width="284" alt="image" src="https://user-images.githubusercontent.com/25154432/170072244-21c9ceab-cf63-4ce1-ab67-b0d8d8f65244.png">

<img width="828" alt="image" src="https://user-images.githubusercontent.com/25154432/170072496-84ced782-5265-456b-ac81-36445336d4d9.png">

**Comment by AtomAlpaca** [comment]
已在 `Firefox` 通过 `Search Engines Helper` 实现
