### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by tsangbor** [RimoChan/sese-engine#16]
`  File "人服务器.py", line 22
    from rimo_utils.计时 import 计时
                    ^
SyntaxError: invalid syntax`

想知道遇到這問題該怎麼辦

**Comment by RimoChan** [comment]
看起来像是环境的问题，你能尽可能详尽地告诉我你的环境是什么吗？

**Comment by tsangbor** [comment]
確實，後來索性就直接在換一台伺服器來跑了
順便想詢問當出現 '队列空了，坏！' 這個時候是繼續等待還是需要操作什麼呢？
是不是只要停掉tmux，重跑了就是資料都清空了？

謝謝作者大大的速度支援

**Comment by RimoChan** [comment]
会积累到差不多1G内存才会写硬盘，所以停掉tmux数据会丢失这一部分的数据。
「队列空了，坏」是一个警告，它有可能没事也有可能有事，实际上爬虫程序有在继续跑吗？

**Comment by tsangbor** [comment]
原先已經抓取快2G資料，搜尋是可以有資料顯示
但後來我將入口網址替換掉，就無法搜尋到結果了
所以我才想問，是不是停掉tmux後，程序停止在啟動所有資料就要重新爬過

**Comment by RimoChan** [comment]
那不应该啊。
我猜是不是你把启动路径变了，默认的保存位置我写的是相对路径……

**Comment by tsangbor** [comment]
我啟動路徑沒更換噎，我是改了入口網址
我也認為照理應該都是有寫入的，理當應該是可以搜尋到結果才是
我在慢慢研究看看，謝謝你的搜索引擎，非常好玩也很有幫助

**Comment by RimoChan** [comment]
嗯……好吧，这个现象我也没有头绪，还是你来帮我研究一下看看是不是bug吧……

**Comment by tsangbor** [comment]
不不不！應該是我的python功力太嫩了
還是非常感謝你的回覆
