### ISSUE TITLE
curl测试似乎有问题

### ISSUE THREAD

**Issue by gitchw** [RimoChan/sese-engine#18]
运行启动.sh输出为：
内存键数: 0it [00:00, ?it/s] * Serving Flask app '收获服务器' (lazy loading)
 * Environment: productiont/s]/s]
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
访问url数: 1it [00:03,  3.01s/it]                            队列空了，坏！
  0%|                               | 0/150 [00:05<?, ?it/s]
访问url数: 1it [00:08,  8.63s/it]   | 0/150 [00:00<?, ?it/s]
访问成功url数: 0it [00:08, ?it/s]dTimeout: 0it [00:00, ?it/s]
[上网.py:110]reppy.exceptions.ReadTimeout: 1it [00:00,  3.14it/s]

运行curl http://127.0.0.1:4950/search?q=test
提示为：curl: (7) Failed to connect to 127.0.0.1 port 4950: 拒绝连接

是项目没有正常启动嘛？QAQ

**Comment by RimoChan** [comment]
啊，默认端口是80，不是4950了，我改一下……

**Comment by RimoChan** [comment]
「队列空了，坏！」一般是因为配置的默认入口是wikipedia，如果你连不上的话就给它换一个别的网站吧……

**Comment by gitchw** [comment]
了解了，谢谢！不过在哪里修改呀？Σ(|||▽||| )另外，我是否可以在能访问维基的服务器上运行一段时间，再把整个项目文件夹拷贝下来呀？这样能保存爬到数据嘛？主要是因为改成国内的一些的，我担心被ban(o´艸`)
表述的可能不是很清楚，见谅QAQ

**Comment by RimoChan** [comment]
> 了解了，谢谢！不过在哪里修改呀？Σ(|||▽||| )另外，我是否可以在能访问维基的服务器上运行一段时间，再把整个项目文件夹拷贝下来呀？这样能保存爬到数据嘛？主要是因为改成国内的一些的，我担心被ban(o´艸`) 表述的可能不是很清楚，见谅QAQ

在 `配置.py` 里改。可以把整个文件夹拷贝下来。

**Comment by gitchw** [comment]
`load_model` does not return WordVectorModel or SupervisedModel any more, but a `FastText` object which is very similar.

emm这是我的配置有问题嘛

**Comment by RimoChan** [comment]
不是，这不是一个问题。此外，这个错误提示无法关闭是FastText的问题。

**Comment by gitchw** [comment]
感谢解答！
