### ISSUE TITLE
提建议，提BUG

### ISSUE THREAD

**Issue by vlinux** [RimoChan/sese-engine#20]
兄弟说实话，这个项目还是有一些BUG的，该有不通用性，但不得不承认他是一个有趣有意思的项目，我很喜欢，但我并不是做Py开发的，我在Macos的系统上，运行它。是失败的，报语法错误
<img width="483" alt="image" src="https://user-images.githubusercontent.com/73208462/180927427-155f0c88-b063-4ab2-9548-a8f646ba20ad.png">
还有就是可以能出一个，前后端的安装教程吗？又或者说，可以完善一下Docker部署教程吗？你文档中提到的Docker部署，非常简陋，当然对老手来说可能很轻车熟路，但对新手来说非常的不通俗易懂。
如果可以当然我希望，可以将前后端一并打包成镜像。这样的话我运行一个镜像然后映射端口就可以直接进行使用

**Comment by RimoChan** [comment]
我也没有用Docker部署过……开源的含义就是大家一起贡献代码嘛，你也可以来帮我或者帮sese-engine-docker补充文档

**Comment by RimoChan** [comment]
然后这个错误我猜是环境的问题，毕竟我手头只有windows和linux，没有mac所以也没办法测试，这个时候就要靠网友的力量了。

我怀疑这是因为mac中有python2，所以启动命令的python指向了python2，也许你可以把所有的python命令修改成特定的可执行文件再试试？

**Comment by vlinux** [comment]
是这样的，我已经将系统中的默认Python指向3.8，并且在PIP安装依赖的时候也是使用的pip3.8，并且是官方的源。我很希望我能够为该项目贡献代码，但目前我想先在我的本地跑起来，然后我会构建一个前后端一体的镜像出来供大家使用！不知道作者您是否尝试过别的Python版本呢？还有就是我的确使用Docker部署的时候会出现坏块这种类似的日志


在 2022年7月26日 ***@***.***> 写道：


然后这个错误我猜是环境的问题，毕竟我手头只有windows和linux，没有mac所以也没办法测试，这个时候就要靠网友的力量了。
我怀疑这是因为mac中有python2，所以启动命令的python指向了python2，也许你可以把所有的python命令修改成特定的可执行文件再试试？

**Comment by RimoChan** [comment]
坏耶，我也不知道到底是什么问题，这样看来只能你自己试试了。
如果找不到头绪就放弃吧，等等看其他用户有没有对mac环境和python同时都比较熟悉的……

**Comment by vlinux** [comment]
好的 还是很感谢老兄，麻烦问一下我们有QQ交流群之类的吗？


在 2022年7月26日 ***@***.***> 写道：


坏耶，我也不知道到底是什么问题，这样看来只能你自己试试了。
 如果找不到头绪就放弃吧，等等看其他用户有没有对mac环境和python同时都比较熟悉的……

**Comment by RimoChan** [comment]
没有QQ交流群，我们现在只有tg水群了
