### ISSUE TITLE
作者我想问下，这个项目启动后save-data目录达到多么大的容量，他才可以成功搜索到

### ISSUE THREAD

**Issue by vlinux** [RimoChan/sese-engine#22]
作者我想问下，这个项目启动后save-data目录达到多么大的容量，他才可以成功搜索到

**Comment by vlinux** [comment]
还有就是这个容量我该如何控制呢？他是一直增长的吗？那应该不管多大的服务器都不行吧？还是说他有一个峰值容量，等达到了那个容量，就会？？？？？自动清除一些数据从而一直保持这个容量？ 
有个好消息 在我刚提这个issues的时候，我成功的搜到了数据，这时候我看我的save-data目录有2.2的数据量。
现在是在本地跑，我想把它转移到云上服务器，所以才问您这个容量有峰值控制么？

**Comment by RimoChan** [comment]
理论上是没有峰值的，但是硬盘增长会越来越慢。
等云服务器大限已到的时候你就得给它加硬盘了。

**Comment by vlinux** [comment]
阿这，冒昧的问一下，这这这，您的demo站点现在容量有多大了呢

**Comment by RimoChan** [comment]
我有一段时间没去看它了，5月的时候大概50G这样。
数据在这里: https://github.com/RimoChan/internet-dataset

**Comment by RimoChan** [comment]
啊，这是打包过的，实际上可能还要大一点，那就算60G吧
