### ISSUE TITLE
如何在树莓派上部署

### ISSUE THREAD

**Issue by mengguyi** [RimoChan/sese-engine#25]
本issue是在记录我在树莓派上部署的一些过程，有可能会帮到你。但请不要拿来主义。其中一些方法可能会~~因人而异~~因网而异

1. 首先你需要有一个树莓派（我这里是4B，其他的不知道能不能部署）
2. [ubuntu20.04](https://cdimage.ubuntu.com/releases/20.04.5/release/ubuntu-20.04.5-preinstalled-server-arm64+raspi.img.xz)

为什么用ubuntu20.04？

因为ubuntu20.04自带的python是python3.8

把ubuntu20.04烧写到TF卡并插入树莓派&&配置好ssh完成初始化（这步不用写吧）

`git clone https://github.com/RimoChan/sese-engine.git`

另外用apt安装pip，具体包名叫什么我忘了。终端里执行一下`pip`就有提示

你要是没用apt安装pip大概率也不会装`gcc`，`g++`之类的。下面安装依赖肯定出错

到用pip安装依赖这一步就要注意了

如果用用`pip install -r requirements.txt`会提示错误（好像是和ruby相关的）

我照着`requirements.txt`直接用`pip`一个一个安装的

到此基本完成了，如果你需要使用代理，看一下`启动.sh`或`启动.cmd`里注释的内容

代理这块填自己的。如果你没有代理。记得把`配置.py`里的入口改一下

**Comment by RimoChan** [comment]
仓库里的启动脚本修好啦！
