### ISSUE TITLE
希望改进文档

### ISSUE THREAD

**Issue by LittleYe233** [RimoChan/sese-engine#3]
在 Arch Linux for ARM 实际测试该仓库，发现文档部分内容说明较模糊，希望能对文档做出改进：

- 启动命令：本仓库根路径下存在许多 Python 代码文件，但没有明显注明执行哪个文件可以启动；
- Python 版本：本程序所需的部分依赖包对 Python 3.10 兼容性差，重新安装 Python 3.8 可以正常安装这些依赖包，希望在文档中注明适宜的 Python 版本。

**Comment by RimoChan** [comment]
没有白发贫乳傲娇双马尾萝莉我现在没有写文档的动力了……

**Comment by RimoChan** [comment]
好，过了3个月我终于更新了！
