### ISSUE TITLE
小小的建议:希望增加ip代理池

### ISSUE THREAD

**Issue by jrz233** [RimoChan/sese-engine#33]
弄不弄无所谓，希望能看看
因为我ip被好几个网站拦截了，如果可以希望弄一个
例子:http://t.csdn.cn/bFh8V
免费代理ip:http://www.ip3366.net/free/

**Comment by RimoChan** [comment]
ip被封说明打得还不够散，你把配置里的爬取集中度减0.1，或者把爬虫冷却时间加3应该就可以了。

**Comment by jrz233** [comment]
> ip被封说明打得还不够散，你把配置里的爬取集中度减0.1，或者把爬虫冷却时间加3应该就可以了。

好吧~_~
