### ISSUE TITLE
对了，我们有交流群吗（是个群就行）

### ISSUE THREAD

**Issue by mengguyi** [RimoChan/sese-engine#39]
就是交流您开发的软件的交流群
除了https://t.me/+xd-6jbjoQdA2ZWU9 以有没有交流技术的群

**Comment by RimoChan** [comment]
这个群就是交流技术的群！

**Comment by mengguyi** [comment]
啊知道了

**Comment by manny1185** [comment]
请问交流sese的方式在哪里？这个issue分享的链接已失效。

**Comment by manny1185** [comment]
在作者主页发现tg群聊，出现如下问题，请问应该怎么加群？
![image](https://github.com/RimoChan/sese-engine/assets/74816299/f6ac8de5-6de0-4601-b192-bce5217998e2)

**Comment by RimoChan** [comment]
啊，你是不是在用ios？你搜索1下「telegram限制ios」……
