### ISSUE TITLE
请问爬取的数据源来自于哪里？是否可以自定义？

### ISSUE THREAD

**Issue by fengguowudi** [RimoChan/sese-engine#40]

**Comment by RimoChan** [comment]
数据来自遍历互联网，就是配置.py的`入口`开始的最大的连通图，所以它很难自定义……

**Comment by fengguowudi** [comment]
我的意思就是怎么遍历？基于wiki的关键词然后在其他搜索引擎找吗？

**Comment by RimoChan** [comment]
就是你把每个url当成点，当url a有到url b的链接时，点a和点b之间会有1条边，然后在这个连通图上做一个魔改的bfs

**Comment by fengguowudi** [comment]
> 就是你把每个url当成点，当url a有到url b的链接时，点a和点b之间会有1条边，然后在这个连通图上做一个魔改的bfs

理解了
