### ISSUE TITLE
安装依赖报错

### ISSUE THREAD

**Issue by fengguowudi** [RimoChan/sese-engine#41]
python版本:3.9
系统：Debian11

pip install -r requirements.txt
运行该命令，出现以下报错

https://pastebin.com/raw/PnZcXa0J

**Comment by RimoChan** [comment]
你的Python太新了，得用3.8。
这是reppy的问题，但是由于 #35 ，我没法把它换掉。

**Comment by fengguowudi** [comment]
https://pastebin.com/raw/w7NvTUdG

**Comment by fengguowudi** [comment]
3.8还是有报错。

**Comment by RimoChan** [comment]
那先升级一下pip试试？这个编码问题可能是pip的bug

**Comment by fengguowudi** [comment]
https://pastebin.com/raw/1tvfV3FB

**Comment by fengguowudi** [comment]
升级完还是error

**Comment by RimoChan** [comment]
嗯，我觉得这是因为依赖里面也有中文导致的。但我认为这还是一个pip的bug，因为你的系统默认编码是latin-1，也许你把它改成gbk可以解决这个问题？

**Comment by fengguowudi** [comment]
https://pastebin.com/raw/mdQVWd0w

运行报错。。。

**Comment by fengguowudi** [comment]
依赖已经装好了啊。

https://pastebin.com/raw/hCYTQku2

**Comment by RimoChan** [comment]
看来环境还没有配好，你的Python没有lzma，你得自己去找一下`ModuleNotFoundError: No module named '_lzma'`该怎么办……

**Comment by RimoChan** [comment]
默认配置好像要放3个小时，你的网速快的话会再短一些

**Comment by RimoChan** [comment]
嗯，我不知道发生了什么，能提供一些更详细的现场信息吗？或者你自己找一找可能有什么不对劲的地方？

**Comment by fengguowudi** [comment]
找到问题了。现在浏览器不允许混用https和http。。。。

**Comment by RimoChan** [comment]
![4CB99B0F0CA966FC908CDFB6BA106B58](https://user-images.githubusercontent.com/20064807/213402292-32beb08a-7982-4310-9b4b-622f7f7887c2.png)
