### ISSUE TITLE
希望支持高级搜索语法

### ISSUE THREAD

**Issue by fengguowudi** [RimoChan/sese-engine#42]
例如 "搜索内容" 是完整包含关键词

**Comment by RimoChan** [comment]
其实现在的后端实现没有办法支持包含完整关键词，因为没有存原始内容……

**Comment by fengguowudi** [comment]
那。。。怎么保证内容和搜索内容是吻合度较高呢

**Comment by RimoChan** [comment]
没事，我有奇怪的算法可以让吻合度适当地高一些！

**Comment by fengguowudi** [comment]
就。你可以试试搜索 我的世界 会自动切为 我 的 世界 三个关联词。然后就官网都找不到（）

**Comment by RimoChan** [comment]
![image](https://user-images.githubusercontent.com/20064807/213607847-1c7cf813-4591-4cfb-bba2-8a4621b3359e.png)

**Comment by RimoChan** [comment]
因为反向链接和标题中连续的关键词都会加权，所以一般情况下是能搜到官网的，但是minecraft的官网确实没有说它叫「我的世界」……

**Comment by fengguowudi** [comment]
指网易的那个（）

**Comment by fengguowudi** [comment]
![image](https://user-images.githubusercontent.com/55879152/213621478-d4a48d6e-fab9-4df9-b567-cfc1c2b06aaf.png)

**Comment by RimoChan** [comment]
不许玩网易，快去官网下载！

**Comment by fengguowudi** [comment]
不是（）我搜minecraft也出不来国际版官网啊

**Comment by RimoChan** [comment]
这是另一个问题，因为www.minecraft.net有反爬……

**Comment by fengguowudi** [comment]
那网易版的为啥搜不出来呢。

**Comment by RimoChan** [comment]
我怀疑只是权重不够，被其他结果挤掉了，不过这个还需要再调查一下

**Comment by fengguowudi** [comment]
![image](https://user-images.githubusercontent.com/55879152/213962653-0ebd5e26-ec68-4c9e-9ecd-cef11e0f76dd.png)

我搜索 1

好像不管等几天数据量都是11000欸（）
不是应该越来越多吗

**Comment by RimoChan** [comment]
哦，你要改`配置.py`里的`单键最多url`，这个配置是用来省硬盘的，每个词只会记录权重最高的11000条结果。

**Comment by fengguowudi** [comment]
还有 `site:网址` 不能直接这么搜索
必须是 `site:网址 内容` 才能搜索
希望优化一下允许直接搜某个url下的内容

**Comment by RimoChan** [comment]
嗯，这个可以做。以及这个issue已经太长了，你要提新需求要新开一个issue。
