### ISSUE TITLE
关于自定义

### ISSUE THREAD

**Issue by BiDuang** [RimoChan/sese-engine#5]
黄桑，请问给部署于自己服务器上的此项目进行自定义（包括网页和引擎）是被允许的吗？修改后的网页仍将保留指向此处的链接与作者署名。
再分发应该不行吧。

**Comment by RimoChan** [comment]
无物为真，诸行皆可！

**Comment by BiDuang** [comment]
> 无物为真，诸行皆可！

好深奥（话说黄桑回消息怎么这么快）

**Comment by RimoChan** [comment]
> > 无物为真，诸行皆可！
> 
> 好深奥（话说黄桑回消息怎么这么快）

因为GitHub会发邮件，所以我会马上收到消息……

**Comment by BiDuang** [comment]
上班刷刷github不算摸鱼罢（笑

**Comment by BiDuang** [comment]
> 无物为真，诸行皆可！

所以非营利的再分发是可以的？

**Comment by RimoChan** [comment]
> > 无物为真，诸行皆可！
> 
> 所以非营利的再分发是可以的？

对！
我想起来我又忘记加协议了，等等我给它加上这个: https://github.com/RimoChan/Je-Suis-Le-Deluge

**Comment by BiDuang** [comment]
> > > 无物为真，诸行皆可！
> > 
> > 
> > 所以非营利的再分发是可以的？
> 
> 对！ 我想起来我又忘记加协议了，等等我给它加上这个: https://github.com/RimoChan/Je-Suis-Le-Deluge
所以黄桑的良心多可靠呢?(doge)

**Comment by RimoChan** [comment]
> > > > 无物为真，诸行皆可！
> > > 
> > > 
> > > 所以非营利的再分发是可以的？
> > 
> > 
> > 对！ 我想起来我又忘记加协议了，等等我给它加上这个: https://github.com/RimoChan/Je-Suis-Le-Deluge
> > 所以黄桑的良心多可靠呢?(doge)

我不听我不听
