### ISSUE TITLE
好，新问题

### ISSUE THREAD

**Issue by TNXG** [RimoChan/sese-engine#6]
```
Warning : `load_model` does not return WordVectorModel or SupervisedModel any more, but a `FastText` object which is very similar.
Traceback (most recent call last):
  File "收获服务器.py", line 13, in <module>
    from utils import netloc, json_loads, 小清洗, 好ThreadPoolExecutor
  File "D:\sese-engine\Server\utils.py", line 108, in <module>
    lang_model = fasttext.load_model('lid.176.ftz')
  File "C:\Program Files\python\lib\site-packages\fasttext\FastText.py", line 441, in load_model
    return _FastText(model_path=path)
  File "C:\Program Files\python\lib\site-packages\fasttext\FastText.py", line 98, in __init__
    self.f.loadModel(model_path)
ValueError: lid.176.ftz cannot be opened for loading!
```

**Comment by RimoChan** [comment]
再pull一下吧，我把模型放进来了……

**Comment by TNXG** [comment]
> 再pull一下吧，我把模型放进来了……

好，让我继续

别的文件都有
`ModuleNotFoundError: No module named 'rimo_utils'`

回,py显示
`Warning : `load_model` does not return WordVectorModel or SupervisedModel any more, but a `FastText` object which is very similar.`

**Comment by RimoChan** [comment]
我忘记把rimo-utils==1.8.0加到requirements.txt里啦！
那个Warning没办法，是库的问题。然后进程没有动是正常的，`回.py` 这个进程是重新计算反向链接的，它只会在每天的0点工作一次。

**Comment by TNXG** [comment]
> 我忘记把rimo-utils==1.8.0加到requirements.txt里啦！ 那个Warning没办法，是库的问题。然后进程没有动是正常的，`回.py` 这个进程是重新计算反向链接的，它只会在每天的0点工作一次。

不懂继续问

上网.py
`Warning : `load_model` does not return WordVectorModel or SupervisedModel any more, but a `FastText` object which is very similar.
访问url数: 0it [00:00, ?it/s]          Traceback (most recent call last):
  File "上网.py", line 189, in <module>
    bfs(入口)
  File "上网.py", line 171, in bfs
    q = 重整(新q)
  File "上网.py", line 138, in 重整
    a = random.choices(url_list, weights=map(喜欢, url_list), k=min(30000, len(url_list)//5+100))
  File "C:\Program Files\python\lib\random.py", line 406, in choices
    total = cum_weights[-1] + 0.0   # convert to float
IndexError: list index out of range
访问url数: 1it [00:05,  5.32s/it]
ConnectionException: 1it [00:00,  3.31it/s]`

人服务器

`Traceback (most recent call last):
  File "人服务器.py", line 42, in <module>
    with open('./data/屏蔽词.json', encoding='utf8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './data/屏蔽词.json'`

**Comment by RimoChan** [comment]
`上网.py` 的这个错误是因为它的队列空了，我刚才改了改判断条件。原因可能是默认配置的入口是 https://zh.wikipedia.org/ ，在中国的服务器访问不了它，你得换个网站。
`人服务器.py` 的这个我刚才修好了，你再pull一下吧。

**Comment by manny1185** [comment]
提问，目前回.py对应的休眠时间是“t = (48 - now.hour + 2) * 3600”，请问这个时间有什么特别的设置吗，还是可以根据自己的需要调整？

**Comment by RimoChan** [comment]
你要开1个新issue……因为`回.py`资源消耗很大，会导致人服务器处理请求变慢，所以让它半夜2点开始工作。
