### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by TNXG** [RimoChan/sese-engine#7]
1. 来个抓取最终分数较高的网站的icon
2. 再来个记录网址抓取时间，并且根据时间的延长降低网站的最终分数避免大量的过期数据（）

~~怪得很，issues是怎么添加标签的来着~~

**Comment by RimoChan** [comment]
你说的很有道理，不过这个改动会影响旧的数据，而且我不确定我的硬盘还够不够，我验证一段时间再上线吧！

**Comment by RimoChan** [comment]
我觉得把时间戳加在「url-词」的对上，代价还是太大了。这次我先把时间戳加在域名上吧，验证1天再push。

**Comment by RimoChan** [comment]
时间戳有啦！
